### ISSUE TITLE
Wrong mouse position

### ISSUE THREAD

**Issue by songmarez** [Frizz925/gbf-autopilot-poker#4]
the bot run test and start completely fine
![test](https://user-images.githubusercontent.com/34344789/35724653-d64c0d9c-0841-11e8-99d2-3c76c29bd380.PNG)

but when i start using poker bot extension the mouse is in wrong position, which is in the red circle only
![run](https://user-images.githubusercontent.com/34344789/35724727-27924df6-0842-11e8-817d-d37849eee75b.PNG)

here is the log file
![start](https://user-images.githubusercontent.com/34344789/35724739-32b6e4b2-0842-11e8-9436-51fde2df1469.PNG)
![start1](https://user-images.githubusercontent.com/34344789/35724746-3777923a-0842-11e8-9632-e1aaa5ab6c43.PNG)

**Comment by Frizz925** [comment]
Please use the [bug reporting template](https://github.com/Frizz925/gbf-autopilot/wiki/Bug-Reporting) when opening a new issue.

**Comment by Frizz925** [comment]
Also, can you please check if this problem also exists outside of the poker extension? I need to know whether the problem is isolated either in the extension or the input controller.

**Comment by Frizz925** [comment]
Yeah the controller is not scale-aware yet, be it display scaling, browser zoom, or game size. Leave them on 1.0x, 100%, and medium to avoid further problems.

**Comment by Frizz925** [comment]
I'll make the controller support variable scaling in the future. You can follow the progress here https://github.com/Frizz925/gbf-autopilot/issues/20.
